### ISSUE TITLE
alex_net.py in models/future and AlexNet defined in models/multi_layer/convolutional_network.py

### ISSUE THREAD

**Issue by skylarbpayne** [vitruvianscience/OpenDeep#1]
Perhaps rename convolutional_network.py to alex_net.py and remove alex_net.py from futures/ to make it more clear?

**Comment by mbeissinger** [comment]
Ah yes, the futures/ folder is meant to be planned networks to implement - that folder shouldn't exist once the package reaches beta. I'm thinking convolutional_network should contain a generic class for convnets where you can specify the types of convolutional and fully-connected/dropout layers, as well as the specific AlexNet implementation in a different subclass. What do you think is best for clarity?

**Comment by skylarbpayne** [comment]
Yeah I figured. I agree with that; a standard ConvNet should go in convolutional_network. Then rename the AlexNet file to alex_net or something more indicative of what it is. Lastly, remove that file from futures. In some sense, this kind of acts as a "Todo list". So deleting the file is like marking it off :).

**Comment by mbeissinger** [comment]
Yep! That is the plan!
