### ISSUE TITLE
Python3 build

### ISSUE THREAD

**Issue by nerdcha** [vitruvianscience/OpenDeep#14]
Howdy! OpenDeep looks great and I'm keen to get it working on [Kaggle Scripts](https://www.kaggle.com/scripts). I had a go at building it in our [Python Docker container](https://github.com/Kaggle/docker-python), but hit a string/bytes error in the setup script:

    File "setup.py", line 49, in <module>
      long_description=read('README.rst'),
    File "setup.py", line 28, in read
      return sep.join(buf)
    TypeError: sequence item 0: expected str instance, bytes found

Tried a few hacky workarounds, but couldn't get it to land. Is this a Python3 issue? Any ideas on how to fix it?

**Comment by ppwwyyxx** [comment]
I don't think python3 is supported, considering the underlying libraries like Theano.
 Maybe you should try python2.

**Comment by ppwwyyxx** [comment]
I don't think python3 is supported, considering the underlying libraries like Theano.
 Maybe you should try python2.

**Comment by nerdcha** [comment]
Yeah, thanks, but no. We already have Theano, Keras and Lasagne fully operational, so I don't think that's it.

**Comment by mbeissinger** [comment]
I'll look into this, thanks for the heads up!

**Comment by mbeissinger** [comment]
Was able to look into it and fix today - had to do with opening files with binary mode in Python 3. It works now in Python 3.4.
