### ISSUE TITLE
Refactoring in develop: a930b977 breaks convolutional_network.py

### ISSUE THREAD

**Issue by mcfletch** [vitruvianscience/OpenDeep#18]
Trivial fix here, the import can be done as:

Softmax as SoftmaxLayer

in opendeep/models/multi_layer/convolutional_network.py

or the name change could be reverted, as all of the documentation uses the SoftmaxLayer name.

HTH

**Comment by webmaven** [comment]
:+1: 

@mbeissinger do you have a preference as to which way to resolve the conflict? I'll gladly make a PR.

P.S. @mcfletch, long time no see!

**Comment by vitruvianscience** [comment]
Sorry for the delay - was traveling last week. I'm actually in the middle of a rewrite in the develop branch (moving over to a new Model interface). The single-layer convolutions work now, you can see an example of LeNet5 in the Tutorials section. This issue will be fixed soon!
