### ISSUE TITLE
Zip objects not indexable in Python3

### ISSUE THREAD

**Issue by MichaelPaddon** [vitruvianscience/OpenDeep#21]
On line 111 of opendeep/models/container/prototype.py, current inputs is calculated as follows:

    current_inputs = zip(previous_out_sizes, previous_outs)

In Python2, zip() returns a list, but in Python3 it returns an iterable zip object. This causes a failure later, when calling code tries to index the result. A simple fix is to wrap the expression in list().

**Comment by vitruvianscience** [comment]
Fixed in the develop branch - merging to master soon.
