### ISSUE TITLE
Spurious warning about default file name

### ISSUE THREAD

**Issue by MichaelPaddon** [vitruvianscience/OpenDeep#22]
On line 729 of opendeep/models/model.py the default file name is set to "config":

    def save_args(self, args_file="config"):

A call to file_ops.get_extension_type() in the method logs a warning "Didn't recognize file extension..." which is spurious because save_args() later appends ".pkl" to the args_file in this case. Suggested fix is to make the default file name "config.pkl" in the first place. This will have exactly the same default behaviour without the warning.

**Comment by vitruvianscience** [comment]
Fixed in the develop branch - merging to master soon.
