### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by robinliheyi** [vitruvianscience/OpenDeep#27]
I tried your sample code provided under the title "**Tutorial: Your First Model**". However, it seems that there is no such file called "cost" in the directory "utils". As a result, I fail to import _binary_crossentropy_ from _opendeep.utils.cost_.

**Comment by mbeissinger** [comment]
Hmm that seems like an old version of the tutorial - are you looking at [the opendeep.org tutorial?](http://www.opendeep.org/docs/tutorial-first-steps)? Would you mind linking it?

**Comment by robinliheyi** [comment]
Dear Markus,

Thank you so much for replying.

The link is http://www.opendeep.org/v0.0.5/docs/tutorial-your-first-model.
Ah, so I guess it is only meant for the old version 0.05, right?
I checked the webpages for the latest version 0.09. And is there a new
tutorial for how to build a denoising autoencoder?

Best wishes,

Heyi Li

On Thu, Mar 24, 2016 at 6:02 PM, Markus Beissinger <notifications@github.com

**Comment by mbeissinger** [comment]
Sorry for the delay, your comment prompted me to make a denoising autoencoder example using the Prototype container. This led me to find some bugs with sharing parameters and optimization :) so I just fixed those if you want to pull the new version!

Here is the full example to make a denoising autoencoder:
```python
from opendeep.models import Prototype, Dense
from opendeep.models.utils import Noise
from opendeep.optimization.loss import BinaryCrossentropy
from opendeep.optimization import AdaDelta
from opendeep.data import MNIST
from theano.tensor import matrix

from opendeep import config_root_logger
config_root_logger()

print "Getting data..."
data = MNIST()

print "Creating model..."
in_shape = (None, 28*28)
in_var = matrix('xs')
n_hidden = 1000
corrupt_input = Noise(inputs=(in_shape, in_var), noise='salt_and_pepper', noise_level=0.5)
encoder = Dense(inputs=corrupt_input, outputs=n_hidden, activation='sigmoid')
W = encoder.get_param("W")
decoder = Dense(inputs=encoder, outputs=in_shape[1], activation='sigmoid')
DenoisingAutoencoder = Prototype([corrupt_input, encoder, decoder])

print "Training..."
loss = BinaryCrossentropy(inputs=DenoisingAutoencoder.get_outputs(), targets=in_var)

optimizer = AdaDelta(model=DenoisingAutoencoder, loss=loss, dataset=data, epochs=50)
optimizer.train()
```
