### ISSUE TITLE
Error by MemoryDataset

### ISSUE THREAD

**Issue by erogol** [vitruvianscience/OpenDeep#4]
If I init MemoryDataset it raise

OD_DATA = datasets.MemoryDataset(train_np, valid_X=val_np)

ValueError                                Traceback (most recent call last)
<ipython-input-19-762c20f7754c> in <module>()
----> 1 OD_DATA = datasets.MemoryDataset(train_np, valid_X=val_np)

/home/retina18/Downloads/opendeep/opendeep/data/dataset.pyc in __init__(self, train_X, train_Y, valid_X, valid_Y, test_X, test_Y)
    283             self.train_Y = sharedX(numpy.array(train_Y))
    284 
--> 285         if valid_X:
    286             valid_X = numpy.array(valid_X)
    287             self._valid_shape = valid_X.shape

**Comment by vitruvianscience** [comment]
Sorry had that fixed in my development but hadn't pushed. Should be fixed now if you pull.
