### ISSUE TITLE
Training assumes float32, but uses float64 if that's the default configuration

### ISSUE THREAD

**Issue by jimmycallin** [vitruvianscience/OpenDeep#9]
When installing Theano on a 64 bit computer, it uses float64 as default. Running through the hello world example, this causes an error where the training assumes the input is float32.

    from opendeep.models.container import Prototype
    from opendeep.models.single_layer.basic import BasicLayer, SoftmaxLayer
    from opendeep.optimization.adadelta import AdaDelta
    from opendeep.data.standard_datasets.image.mnist import MNIST

    mlp = Prototype()
    mlp.add(BasicLayer(input_size=28*28, output_size=512, activation='rectifier', noise='dropout'))
    mlp.add(BasicLayer(output_size=512, activation='rectifier', noise='dropout'))
    mlp.add(SoftmaxLayer(output_size=10))

    trainer = AdaDelta(model=mlp, dataset=MNIST())
    trainer.train()

This raises:

    TypeError: Cannot convert Type TensorType(float64, matrix) (of Variable Subtensor{int32:int32:}.0) into Type TensorType(float32, matrix). You can try to manually convert Subtensor{int32:int32:}.0 into a TensorType(float32, matrix).

**Comment by mbeissinger** [comment]
Ah thanks for pointing that out! 

I'll have to go through to check all the conversions, but for now you should add a theano flag specifying floats to be float32. If you have a .theanorc file, you can do this by adding:

[global]
floatX=float32

Or if you don't have the .theanorc file, I recommend creating one with the following command:

echo -e "\n[global]\nfloatX=float32\ndevice=gpu\n[mode]=FAST_RUN\n\n[nvcc]\nfastmath=True\n\n[cuda]\nroot=/usr/local/cuda" >> ~/.theanorc

This was done mostly for use on the GPU, which Theano only supports as float32 for all ops.

More reference from Theano here on setting flags/configuration: http://deeplearning.net/software/theano/library/config.html

**Comment by jimmycallin** [comment]
Thanks for the tip.

**Comment by mbeissinger** [comment]
Should be resolved now. Whenever a tensor was created as 'fmatrix' or 'fvector', it specifies to float32. Changing to just 'matrix' or 'vector' uses the theano.config.floatX.

**Comment by jimmycallin** [comment]
Good job!
